from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

TASK_ZLONG_BAND = Button(area={'game': (1224, 544, 1256, 592)},text={'game': ''}, color={'game': (120, 63, 39)}, button={'game': (1224, 544, 1256, 592)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_BAND.png'})
TASK_ZLONG_BAND_CLOSE = Button(area={'game': (1168, 48, 1200, 72)},text={'game': ''}, color={'game': (81, 93, 105)}, button={'game': (1168, 48, 1200, 72)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_BAND_CLOSE.png'})
TASK_ZLONG_CLICK_TOOL = Button(area={'game': (1216, 192, 1264, 232)},text={'game': '+'}, color={'game': (80, 100, 90)}, button={'game': (1216, 192, 1264, 232)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_CLICK_TOOL.png'})
TASK_ZLONG_COME_BAND = Button(area={'game': (904, 608, 1040, 648)},text={'game': '回到帮会'}, color={'game': (109, 149, 199)}, button={'game': (904, 608, 1040, 648)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_COME_BAND.png'})
TASK_ZLONG_ESCAPE_STEP_1 = Button(area={'game': (366, 388, 446, 452)},text={'game': ''}, color={'game': (53, 70, 30)}, button={'game': (366, 388, 446, 452)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_ESCAPE_STEP_1.png'})
TASK_ZLONG_ESCAPE_STEP_2 = Button(area={'game': (390, 471, 451, 519)},text={'game': ''}, color={'game': (78, 78, 35)}, button={'game': (390, 471, 451, 519)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_ESCAPE_STEP_2.png'})
TASK_ZLONG_ESCAPE_STEP_3 = Button(area={'game': (510, 485, 599, 548)},text={'game': ''}, color={'game': (90, 93, 39)}, button={'game': (510, 485, 599, 548)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_ESCAPE_STEP_3.png'})
TASK_ZLONG_ESCAPE_STEP_4 = Button(area={'game': (642, 532, 738, 601)},text={'game': ''}, color={'game': (91, 102, 37)}, button={'game': (642, 532, 738, 601)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_ESCAPE_STEP_4.png'})
TASK_ZLONG_ESCAPE_STEP_5 = Button(area={'game': (658, 428, 726, 481)},text={'game': ''}, color={'game': (100, 110, 41)}, button={'game': (658, 428, 726, 481)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_ESCAPE_STEP_5.png'})
TASK_ZLONG_ESCAPE_STEP_6 = Button(area={'game': (894, 242, 979, 293)},text={'game': ''}, color={'game': (54, 70, 27)}, button={'game': (894, 242, 979, 293)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_ESCAPE_STEP_6.png'})
TASK_ZLONG_ESCAPE_STEP_7 = Button(area={'game': (622, 220, 687, 256)},text={'game': ''}, color={'game': (73, 79, 33)}, button={'game': (622, 220, 687, 256)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_ESCAPE_STEP_7.png'})
TASK_ZLONG_ESCAPE_STEP_8 = Button(area={'game': (586, 314, 626, 343)},text={'game': ''}, color={'game': (227, 209, 70)}, button={'game': (586, 314, 626, 343)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_ESCAPE_STEP_8.png'})
TASK_ZLONG_FAIL = Button(area={'game': (416, 608, 552, 656)},text={'game': '放弃任务'}, color={'game': (93, 124, 167)}, button={'game': (416, 608, 552, 656)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_FAIL.png'})
TASK_ZLONG_FAIL_ABIRT = Button(area={'game': (400, 272, 872, 472)},text={'game': '放弃本次任务，将损失本轮所有剩余的任务次数，确定要放弃吗？取消确定'}, color={'game': (66, 95, 129)}, button={'game': (720, 408, 848, 456)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_FAIL_ABIRT.png'})
TASK_ZLONG_FINISH = Button(area={'game': (416, 280, 864, 464)},text={'game': '今天战龙任务已完成五次，继续任务不会获得个人奖励确定'}, color={'game': (52, 87, 131)}, button={'game': (568, 408, 712, 448)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_FINISH.png'})
TASK_ZLONG_FIRST_LIST = Button(area={'game': (8, 200, 224, 256)},text={'game': '[终结战龙]劲敌去鬼多多帮会使用道'}, color={'game': (114, 112, 78)}, button={'game': (8, 200, 224, 256)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_FIRST_LIST.png'})
TASK_ZLONG_Kill = Button(area={'game': (1016, 320, 1088, 384)},text={'game': ''}, color={'game': (58, 80, 86)}, button={'game': (968, 448, 1128, 488)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_Kill.png'})
TASK_ZLONG_LAST_BEAT = Button(area={'game': (1008, 312, 1096, 400)},text={'game': '战'}, color={'game': (152, 74, 65)}, button={'game': (976, 448, 1128, 496)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_LAST_BEAT.png'})
TASK_ZLONG_LAST_RUN = Button(area={'game': (1008, 312, 1096, 400)},text={'game': ''}, color={'game': (75, 144, 68)}, button={'game': (976, 448, 1128, 496)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_LAST_RUN.png'})
TASK_ZLONG_OUT_MAP_TAG = Button(area={'game': (1056, 112, 1104, 144)},text={'game': 'S'}, color={'game': (60, 79, 40)}, button={'game': (1056, 112, 1104, 144)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_OUT_MAP_TAG.png'})
TASK_ZLOONG_USE_PROP = Button(area={'game': (968, 448, 1128, 496)},text={'game': '使用'}, color={'game': (103, 137, 182)}, button={'game': (968, 448, 1128, 496)}, file={'game': './assets/game/task_zlong/TASK_ZLOONG_USE_PROP.png'})
