from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

TASK_ZLONG_FAIL = Button(area={'game': (0, 192, 200, 240)},text={'game': '1妖兽入侵！'}, color={'game': (68, 39, 66)}, button={'game': (0, 192, 200, 240)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_FAIL.png'})
TASK_ZLONG_FINISH = Button(area={'game': (0, 192, 200, 240)},text={'game': '1妖兽入侵！'}, color={'game': (68, 39, 66)}, button={'game': (0, 192, 200, 240)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_FINISH.png'})
TASK_ZLONG_Kill = Button(area={'game': (0, 192, 200, 240)},text={'game': '1妖兽入侵！'}, color={'game': (68, 39, 66)}, button={'game': (0, 192, 200, 240)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_Kill.png'})
TASK_ZLONG_LAST_BEAT = Button(area={'game': (0, 192, 200, 240)},text={'game': '1妖兽入侵！'}, color={'game': (68, 39, 66)}, button={'game': (0, 192, 200, 240)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_LAST_BEAT.png'})
TASK_ZLONG_LAST_RUN = Button(area={'game': (0, 192, 200, 240)},text={'game': '1妖兽入侵！'}, color={'game': (68, 39, 66)}, button={'game': (0, 192, 200, 240)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_LAST_RUN.png'})
TASK_ZLONG_OUT_MAP_TAG = Button(area={'game': (0, 192, 200, 240)},text={'game': '1妖兽入侵！'}, color={'game': (68, 39, 66)}, button={'game': (0, 192, 200, 240)}, file={'game': './assets/game/task_zlong/TASK_ZLONG_OUT_MAP_TAG.png'})
