from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

TASK_LONG_FIRST_LIST = Button(area={'game': (0, 192, 224, 352)},text={'game': '[旧常]一条龙任务（2/5听说桃花涧里的五色桃花通了灵性，竟快要修成了人形了。快香君魂（0/1）'}, color={'game': (91, 100, 82)}, button={'game': (0, 192, 224, 352)}, file={'game': './assets/game/task_long/TASK_LONG_FIRST_LIST.png'})
TASK_LONG_IS_MAP = Button(area={'game': (832, 136, 872, 152)},text={'game': ''}, color={'game': (88, 52, 16)}, button={'game': (832, 136, 872, 152)}, file={'game': './assets/game/task_long/TASK_LONG_IS_MAP.png'})
TASK_LONG_TASK_RECEIVE = Button(area={'game': (376, 232, 904, 416)},text={'game': '本轮一条龙结束，是否继续领取'}, color={'game': (42, 75, 113)}, button={'game': (720, 408, 856, 456)}, file={'game': './assets/game/task_long/TASK_LONG_TASK_RECEIVE.png'})
