from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

TASK_SM_FIRST_LIST = Button(area={'game': (8, 192, 232, 264)},text={'game': '[师门]巡逻(1/10)到兰若地宫使用师门'}, color={'game': (62, 37, 30)}, button={'game': (8, 192, 232, 264)}, file={'game': './assets/game/task_sm/TASK_SM_FIRST_LIST.png'})
TASK_SM_TASK_FINISH = Button(area={'game': (408, 272, 864, 464)},text={'game': '今日师门任务已全部完成，还可去别处瞧瞧。确定'}, color={'game': (48, 82, 124)}, button={'game': (568, 408, 704, 448)}, file={'game': './assets/game/task_sm/TASK_SM_TASK_FINISH.png'})
TASK_SM_USE_PROP = Button(area={'game': (968, 448, 1128, 496)},text={'game': '使用'}, color={'game': (103, 137, 182)}, button={'game': (968, 448, 1128, 496)}, file={'game': './assets/game/task_sm/TASK_SM_USE_PROP.png'})
