from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

TASK_SM_FIRST_LIST = Button(area={'game': (0, 192, 216, 232)},text={'game': '宝图任务（10/20）'}, color={'game': (64, 65, 34)}, button={'game': (0, 192, 216, 232)}, file={'game': './assets/game/task_sm/TASK_SM_FIRST_LIST.png'})
TASK_SM_SUBMIT_EQUIPMENT_DECITION = Button(area={'game': (408, 312, 872, 464)},text={'game': '（装备上交后将无法找回。取消确定'}, color={'game': (64, 92, 122)}, button={'game': (408, 312, 872, 464)}, file={'game': './assets/game/task_sm/TASK_SM_SUBMIT_EQUIPMENT_DECITION.png'})
TASK_SM_SUBMIT_EQUIPMENT_START = Button(area={'game': (488, 544, 616, 584)},text={'game': '购买其他'}, color={'game': (86, 121, 165)}, button={'game': (488, 544, 616, 584)}, file={'game': './assets/game/task_sm/TASK_SM_SUBMIT_EQUIPMENT_START.png'})
TASK_SM_TASK_FINISH = Button(area={'game': (408, 272, 864, 464)},text={'game': '今日师门任务已全部完成，还可去别处瞧瞧。确定'}, color={'game': (48, 82, 124)}, button={'game': (568, 408, 704, 448)}, file={'game': './assets/game/task_sm/TASK_SM_TASK_FINISH.png'})
TASK_SM_USE_PROP = Button(area={'game': (968, 448, 1128, 496)},text={'game': '使用'}, color={'game': (103, 137, 182)}, button={'game': (968, 448, 1128, 496)}, file={'game': './assets/game/task_sm/TASK_SM_USE_PROP.png'})
TASK_SM_USE_PROP2 = Button(area={'game': (968, 448, 1128, 488)},text={'game': '使用'}, color={'game': (106, 145, 193)}, button={'game': (968, 448, 1128, 488)}, file={'game': './assets/game/task_sm/TASK_SM_USE_PROP2.png'})
