from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

TASK_INSTANCE_EXIT_NOTICE = Button(area={'game': (426, 281, 855, 422)},text={'game': '即将离开副本，是否继续'}, color={'game': (54, 86, 125)}, button={'game': (723, 414, 848, 451)}, file={'game': './assets/game/task_sm/TASK_INSTANCE_EXIT_NOTICE.png'})
TASK_SM_ADVANCED_NOTICE = Button(area={'game': (408, 272, 864, 456)},text={'game': '恭喜你已达成师门贡献升级要求，特进阶为初阶伍长！确定'}, color={'game': (52, 88, 131)}, button={'game': (568, 408, 704, 448)}, file={'game': './assets/game/task_sm/TASK_SM_ADVANCED_NOTICE.png'})
TASK_SM_FIRST_LIST = Button(area={'game': (0, 192, 224, 280)},text={'game': '[师门]历练（9/10）帮杨家镇的青凤放河灯'}, color={'game': (54, 67, 46)}, button={'game': (0, 192, 224, 264)}, file={'game': './assets/game/task_sm/TASK_SM_FIRST_LIST.png'})
TASK_SM_NOTICE_CONFIRM = Button(area={'game': (704, 408, 848, 448)},text={'game': '确认'}, color={'game': (202, 177, 104)}, button={'game': (704, 408, 848, 448)}, file={'game': './assets/game/task_sm/TASK_SM_NOTICE_CONFIRM.png'})
TASK_SM_OUT_MAP_TAG = Button(area={'game': (1056, 112, 1104, 144)},text={'game': 'S'}, color={'game': (60, 79, 40)}, button={'game': (1056, 112, 1104, 144)}, file={'game': './assets/game/task_sm/TASK_SM_OUT_MAP_TAG.png'})
TASK_SM_SUBMIT_EQUIPMENT_DECITION = Button(area={'game': (408, 312, 872, 464)},text={'game': '（装备上交后将无法找回。取消确定'}, color={'game': (64, 92, 122)}, button={'game': (408, 312, 872, 464)}, file={'game': './assets/game/task_sm/TASK_SM_SUBMIT_EQUIPMENT_DECITION.png'})
TASK_SM_SUBMIT_EQUIPMENT_REAL = Button(area={'game': (336, 552, 440, 584)},text={'game': '上交'}, color={'game': (117, 160, 216)}, button={'game': (336, 552, 440, 584)}, file={'game': './assets/game/task_sm/TASK_SM_SUBMIT_EQUIPMENT_REAL.png'})
TASK_SM_SUBMIT_EQUIPMENT_START = Button(area={'game': (488, 544, 616, 584)},text={'game': '购买其他'}, color={'game': (86, 121, 165)}, button={'game': (488, 544, 616, 584)}, file={'game': './assets/game/task_sm/TASK_SM_SUBMIT_EQUIPMENT_START.png'})
TASK_SM_SUBMIT_EQUIPMENT_STORE = Button(area={'game': (328, 448, 472, 496)},text={'game': 'NPC商店'}, color={'game': (54, 83, 117)}, button={'game': (328, 448, 472, 496)}, file={'game': './assets/game/task_sm/TASK_SM_SUBMIT_EQUIPMENT_STORE.png'})
TASK_SM_TASK_FINISH = Button(area={'game': (408, 272, 864, 464)},text={'game': '今日师门任务已全部完成，还可去别处瞧瞧。确定'}, color={'game': (48, 82, 124)}, button={'game': (568, 408, 704, 448)}, file={'game': './assets/game/task_sm/TASK_SM_TASK_FINISH.png'})
TASK_SM_USE_PROP = Button(area={'game': (968, 448, 1128, 496)},text={'game': '使用'}, color={'game': (103, 137, 182)}, button={'game': (968, 448, 1128, 496)}, file={'game': './assets/game/task_sm/TASK_SM_USE_PROP.png'})
TASK_SM_USE_PROP2 = Button(area={'game': (968, 448, 1128, 488)},text={'game': '使用'}, color={'game': (106, 145, 193)}, button={'game': (968, 448, 1128, 488)}, file={'game': './assets/game/task_sm/TASK_SM_USE_PROP2.png'})
