from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

SHOPPING_FABAO_SEARCH = Button(area={'game': (768, 608, 1128, 656)},text={'game': '关注此类法宝搜索'}, color={'game': (180, 158, 95)}, button={'game': (952, 616, 1120, 656)}, file={'game': './assets/game/shopping/SHOPPING_FABAO_SEARCH.png'})
SHOPPING_NPC = Button(area={'game': (928, 608, 1096, 648)},text={'game': '购买'}, color={'game': (206, 181, 106)}, button={'game': (928, 608, 1096, 648)}, file={'game': './assets/game/shopping/SHOPPING_NPC.png'})
SHOPPING_NPC_CLOSE = Button(area={'game': (1176, 56, 1200, 72)},text={'game': ''}, color={'game': (124, 138, 149)}, button={'game': (1176, 56, 1200, 72)}, file={'game': './assets/game/shopping/SHOPPING_NPC_CLOSE.png'})
SHOPPING_PLAYER = Button(area={'game': (824, 608, 1128, 656)},text={'game': '关注购买'}, color={'game': (186, 164, 100)}, button={'game': (952, 616, 1112, 656)}, file={'game': './assets/game/shopping/SHOPPING_PLAYER.png'})
SHOPPING_PLAYER_CLOSE = Button(area={'game': (1168, 48, 1200, 72)},text={'game': ''}, color={'game': (80, 93, 104)}, button={'game': (1168, 48, 1200, 72)}, file={'game': './assets/game/shopping/SHOPPING_PLAYER_CLOSE.png'})
SHOPPING_PLAYER_CONFIRM = Button(area={'game': (704, 408, 848, 448)},text={'game': '确认'}, color={'game': (202, 177, 104)}, button={'game': (704, 408, 848, 448)}, file={'game': './assets/game/shopping/SHOPPING_PLAYER_CONFIRM.png'})
