from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ACTION_WINDOW_BUTTON1 = Button(area={'game': (600, 232, 704, 256)},text={'game': ''}, color={'game': (68, 109, 147)}, button={'game': (600, 232, 704, 256)}, file={'game': './assets/game/action_window/ACTION_WINDOW_BUTTON1.png'})
ACTION_WINDOW_BUTTON2 = Button(area={'game': (1056, 224, 1160, 256)},text={'game': ''}, color={'game': (54, 89, 121)}, button={'game': (1056, 224, 1160, 256)}, file={'game': './assets/game/action_window/ACTION_WINDOW_BUTTON2.png'})
ACTION_WINDOW_BUTTON3 = Button(area={'game': (608, 320, 688, 352)},text={'game': '参加'}, color={'game': (68, 114, 159)}, button={'game': (608, 320, 688, 352)}, file={'game': './assets/game/action_window/ACTION_WINDOW_BUTTON3.png'})
ACTION_WINDOW_BUTTON4 = Button(area={'game': (1064, 320, 1144, 352)},text={'game': '参加'}, color={'game': (74, 124, 173)}, button={'game': (1064, 320, 1144, 352)}, file={'game': './assets/game/action_window/ACTION_WINDOW_BUTTON4.png'})
ACTION_WINDOW_BUTTON5 = Button(area={'game': (608, 424, 688, 456)},text={'game': '参加'}, color={'game': (67, 114, 159)}, button={'game': (608, 424, 688, 456)}, file={'game': './assets/game/action_window/ACTION_WINDOW_BUTTON5.png'})
ACTION_WINDOW_BUTTON6 = Button(area={'game': (1056, 416, 1144, 456)},text={'game': '参加'}, color={'game': (65, 110, 152)}, button={'game': (1056, 416, 1144, 456)}, file={'game': './assets/game/action_window/ACTION_WINDOW_BUTTON6.png'})
ACTION_WINDOW_BUTTON7 = Button(area={'game': (608, 520, 688, 560)},text={'game': '参加'}, color={'game': (69, 114, 158)}, button={'game': (608, 520, 688, 560)}, file={'game': './assets/game/action_window/ACTION_WINDOW_BUTTON7.png'})
ACTION_WINDOW_BUTTON8 = Button(area={'game': (1056, 520, 1136, 560)},text={'game': '参加'}, color={'game': (66, 111, 154)}, button={'game': (1056, 520, 1136, 560)}, file={'game': './assets/game/action_window/ACTION_WINDOW_BUTTON8.png'})
ACTION_WINDOW_CLOSE = Button(area={'game': (1232, 40, 1256, 64)},text={'game': ''}, color={'game': (66, 72, 75)}, button={'game': (1232, 40, 1256, 64)}, file={'game': './assets/game/action_window/ACTION_WINDOW_CLOSE.png'})
ACTION_WINDOW_TASK_SITE = Button(area={'game': (360, 184, 824, 288)},text={'game': '师门任务参加经验次数0/20活力0/60'}, color={'game': (36, 62, 95)}, button={'game': (360, 184, 824, 288)}, file={'game': './assets/game/action_window/ACTION_WINDOW_TASK_SITE.png'})
ACTION_WINDOW_TASK_TAG = Button(area={'game': (360, 184, 560, 232)},text={'game': '师门任务'}, color={'game': (4, 14, 24)}, button={'game': (600, 208, 704, 256)}, file={'game': './assets/game/action_window/ACTION_WINDOW_TASK_TAG.png'})
