from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ACTION_WINDOW_CLOSE = Button(area={'game': (1232, 40, 1256, 64)},text={'game': ''}, color={'game': (66, 72, 75)}, button={'game': (1232, 40, 1256, 64)}, file={'game': './assets/game/action_window/ACTION_WINDOW_CLOSE.png'})
ACTION_WINDOW_TASK_SITE = Button(area={'game': (360, 184, 824, 288)},text={'game': '师门任务参加经验次数0/20活力0/60'}, color={'game': (36, 62, 95)}, button={'game': (360, 184, 824, 288)}, file={'game': './assets/game/action_window/ACTION_WINDOW_TASK_SITE.png'})
ACTION_WINDOW_TASK_TAG = Button(area={'game': (360, 184, 560, 232)},text={'game': '师门任务'}, color={'game': (4, 14, 24)}, button={'game': (600, 208, 704, 256)}, file={'game': './assets/game/action_window/ACTION_WINDOW_TASK_TAG.png'})
