from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

TASK_RUN_BANK_MAP = Button(area={'game': (112, 40, 424, 128)},text={'game': ''}, color={'game': (52, 62, 57)}, button={'game': (416, 616, 448, 648)}, file={'game': './assets/game/task_run/TASK_RUN_BANK_MAP.png'})
TASK_RUN_FIELD_MAP_END = Button(area={'game': (112, 40, 416, 120)},text={'game': '公'}, color={'game': (61, 72, 68)}, button={'game': (624, 648, 648, 672)}, file={'game': './assets/game/task_run/TASK_RUN_FIELD_MAP_END.png'})
TASK_RUN_FIELD_MAP_START = Button(area={'game': (112, 40, 416, 120)},text={'game': '公'}, color={'game': (61, 72, 68)}, button={'game': (776, 104, 808, 128)}, file={'game': './assets/game/task_run/TASK_RUN_FIELD_MAP_START.png'})
TASK_RUN_VIEW_GOODS = Button(area={'game': (984, 432, 1120, 480)},text={'game': '查看货物'}, color={'game': (83, 129, 164)}, button={'game': (984, 432, 1120, 480)}, file={'game': './assets/game/task_run/TASK_RUN_VIEW_GOODS.png'})
