from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

POP_ACTIVE_FIRST = Button(area={'game': (448, 504, 544, 528)},text={'game': ''}, color={'game': (88, 141, 182)}, button={'game': (456, 544, 512, 600)}, file={'game': './assets/game/pop_frame/POP_ACTIVE_FIRST.png'})
POP_ACTIVE_FIRST_CLOSE = Button(area={'game': (824, 528, 840, 552)},text={'game': ''}, color={'game': (72, 77, 78)}, button={'game': (824, 528, 840, 552)}, file={'game': './assets/game/pop_frame/POP_ACTIVE_FIRST_CLOSE.png'})
POP_APPLY_LEAR_AGREE = Button(area={'game': (1096, 360, 1176, 408)},text={'game': '弯诗倾城申请成为队长是否同意？'}, color={'game': (145, 129, 79)}, button={'game': (1096, 360, 1176, 408)}, file={'game': './assets/game/pop_frame/POP_APPLY_LEAR_AGREE.png'})
POP_APPLY_LEAR_AGREE_ASSIST = Button(area={'game': (928, 248, 1256, 280)},text={'game': ''}, color={'game': (25, 43, 73)}, button={'game': (928, 248, 1256, 280)}, file={'game': './assets/game/pop_frame/POP_APPLY_LEAR_AGREE_ASSIST.png'})
POP_APPLY_LEAR_DISAGREE = Button(area={'game': (960, 360, 1088, 400)},text={'game': '弯诗倾城申请成为队长是否同意？'}, color={'game': (92, 125, 166)}, button={'game': (960, 360, 1088, 400)}, file={'game': './assets/game/pop_frame/POP_APPLY_LEAR_DISAGREE.png'})
POP_APPLY_LEAR_DISAGREE_ASSIST = Button(area={'game': (928, 248, 1256, 280)},text={'game': ''}, color={'game': (25, 43, 73)}, button={'game': (928, 248, 1256, 280)}, file={'game': './assets/game/pop_frame/POP_APPLY_LEAR_DISAGREE_ASSIST.png'})
POP_NPC_DIALOGUE = Button(area={'game': (1216, 456, 1256, 512)},text={'game': ''}, color={'game': (87, 116, 151)}, button={'game': (1064, 464, 1168, 496)}, file={'game': './assets/game/pop_frame/POP_NPC_DIALOGUE.png'})
POP_NPC_DIALOGUE_HORN = Button(area={'game': (528, 536, 560, 568)},text={'game': ''}, color={'game': (74, 91, 107)}, button={'game': (528, 536, 560, 568)}, file={'game': './assets/game/pop_frame/POP_NPC_DIALOGUE_HORN.png'})
POP_NPC_DIALOGUE_SITE = Button(area={'game': (1216, 448, 1256, 512)},text={'game': ''}, color={'game': (80, 107, 139)}, button={'game': (1216, 448, 1256, 512)}, file={'game': './assets/game/pop_frame/POP_NPC_DIALOGUE_SITE.png'})
POP_NPC_TEXT_TAG = Button(area={'game': (1200, 648, 1248, 696)},text={'game': ''}, color={'game': (31, 57, 71)}, button={'game': (1200, 648, 1248, 696)}, file={'game': './assets/game/pop_frame/POP_NPC_TEXT_TAG.png'})
POP_USE_PROP = Button(area={'game': (968, 448, 1128, 496)},text={'game': '使用'}, color={'game': (103, 137, 182)}, button={'game': (968, 448, 1128, 496)}, file={'game': './assets/game/pop_frame/POP_USE_PROP.png'})
SHOPPING_PLAYER_CONFIRM = Button(area={'game': (704, 408, 848, 448)},text={'game': '确认'}, color={'game': (202, 177, 104)}, button={'game': (704, 408, 848, 448)}, file={'game': './assets/game/pop_frame/SHOPPING_PLAYER_CONFIRM.png'})
