from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

GUA_JI = Button(area={'game': (1200, 304, 1264, 392)},text={'game': '挂机'}, color={'game': (103, 91, 70)}, button={'game': (1200, 304, 1264, 392)}, file={'game': './assets/game/mian_window/GUA_JI.png'})
MAP_CHANGE_LINE = Button(area={'game': (1128, 24, 1280, 56)},text={'game': '137，78分线1'}, color={'game': (69, 83, 85)}, button={'game': (1128, 24, 1280, 56)}, file={'game': './assets/game/mian_window/MAP_CHANGE_LINE.png'})
MAP_TITLE = Button(area={'game': (1120, 0, 1280, 32)},text={'game': '蒲家村'}, color={'game': (40, 69, 96)}, button={'game': (1120, 0, 1280, 32)}, file={'game': './assets/game/mian_window/MAP_TITLE.png'})
MARKET = Button(area={'game': (896, 16, 976, 80)},text={'game': '易市'}, color={'game': (133, 99, 64)}, button={'game': (896, 16, 976, 80)}, file={'game': './assets/game/mian_window/MARKET.png'})
SHOPPING = Button(area={'game': (1048, 8, 1120, 80)},text={'game': 'ooll商城'}, color={'game': (125, 91, 67)}, button={'game': (1048, 8, 1120, 80)}, file={'game': './assets/game/mian_window/SHOPPING.png'})
TASK_SELECT = Button(area={'game': (0, 136, 120, 192)},text={'game': '任务'}, color={'game': (134, 166, 193)}, button={'game': (0, 136, 120, 192)}, file={'game': './assets/game/mian_window/TASK_SELECT.png'})
TEAM_NO_SELECT = Button(area={'game': (128, 136, 240, 192)},text={'game': '队伍'}, color={'game': (95, 131, 171)}, button={'game': (128, 136, 240, 192)}, file={'game': './assets/game/mian_window/TEAM_NO_SELECT.png'})
