from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

HOME_ACTIVE = Button(area={'game': (976, 16, 1048, 80)}, color={'game': (121, 106, 70)}, button={'game': (976, 16, 1048, 80)}, file={'game': './assets/game/mian_window/HOME_ACTIVE.png'})
HOME_ACTIVE_BUTTON = Button(area={'game': (984, 24, 1040, 64)}, color={'game': (132, 99, 51)}, button={'game': (984, 24, 1040, 64)}, file={'game': './assets/game/mian_window/HOME_ACTIVE_BUTTON.png'})
HOME_GUA_JI_HAVE = Button(area={'game': (1168, 296, 1280, 392)}, color={'game': (86, 98, 63)}, button={'game': (1168, 296, 1280, 392)}, file={'game': './assets/game/mian_window/HOME_GUA_JI_HAVE.png'})
HOME_GUA_JI_HAVE_BUTTON = Button(area={'game': (1208, 320, 1264, 360)}, color={'game': (81, 80, 71)}, button={'game': (1208, 320, 1264, 360)}, file={'game': './assets/game/mian_window/HOME_GUA_JI_HAVE_BUTTON.png'})
HOME_GUA_JI_NOT = Button(area={'game': (1200, 304, 1264, 392)}, color={'game': (103, 91, 70)}, button={'game': (1200, 304, 1264, 392)}, file={'game': './assets/game/mian_window/HOME_GUA_JI_NOT.png'})
HOME_GUA_JI_NOT_BUTTON = Button(area={'game': (1208, 320, 1264, 360)}, color={'game': (81, 80, 71)}, button={'game': (1208, 320, 1264, 360)}, file={'game': './assets/game/mian_window/HOME_GUA_JI_NOT_BUTTON.png'})
HOME_MAP_LINE = Button(area={'game': (1128, 24, 1280, 56)}, color={'game': (69, 83, 85)}, button={'game': (1128, 24, 1280, 56)}, file={'game': './assets/game/mian_window/HOME_MAP_LINE.png'})
HOME_MAP_TITLE = Button(area={'game': (1120, 0, 1280, 32)}, color={'game': (40, 69, 96)}, button={'game': (1120, 0, 1280, 32)}, file={'game': './assets/game/mian_window/HOME_MAP_TITLE.png'})
HOME_SELECT_TASK = Button(area={'game': (0, 136, 120, 192)}, color={'game': (135, 168, 196)}, button={'game': (0, 136, 120, 192)}, file={'game': './assets/game/mian_window/HOME_SELECT_TASK.png'})
HOME_SELECT_TEAM = Button(area={'game': (128, 136, 192, 192)}, color={'game': (121, 152, 177)}, button={'game': (128, 136, 192, 192)}, file={'game': './assets/game/mian_window/HOME_SELECT_TEAM.png'})
