from qianv_tool.module.base.button import Button
from qianv_tool.module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

HOME_2TEM_FOLLOW = Button(area={'game': (0, 264, 120, 312)},text={'game': '召唤跟随'}, color={'game': (112, 151, 201)}, button={'game': (0, 264, 120, 312)}, file={'game': './assets/game/mian_window/HOME_2TEM_FOLLOW.png'})
HOME_2TEM_FOLLOW_CANCEL = Button(area={'game': (128, 264, 240, 304)},text={'game': '取消跟随'}, color={'game': (107, 148, 200)}, button={'game': (128, 264, 240, 304)}, file={'game': './assets/game/mian_window/HOME_2TEM_FOLLOW_CANCEL.png'})
HOME_3TEM_FOLLOW = Button(area={'game': (0, 320, 120, 368)},text={'game': '召唤跟随'}, color={'game': (106, 144, 191)}, button={'game': (0, 320, 120, 368)}, file={'game': './assets/game/mian_window/HOME_3TEM_FOLLOW.png'})
HOME_3TEM_FOLLOW_CANCEL = Button(area={'game': (128, 320, 248, 368)},text={'game': '取消跟随'}, color={'game': (103, 139, 186)}, button={'game': (128, 320, 248, 368)}, file={'game': './assets/game/mian_window/HOME_3TEM_FOLLOW_CANCEL.png'})
HOME_4TEM_FOLLOW = Button(area={'game': (0, 384, 120, 432)},text={'game': '召唤跟随'}, color={'game': (102, 138, 184)}, button={'game': (0, 384, 120, 432)}, file={'game': './assets/game/mian_window/HOME_4TEM_FOLLOW.png'})
HOME_4TEM_FOLLOW_CANCEL = Button(area={'game': (128, 384, 248, 432)},text={'game': '取消跟随'}, color={'game': (106, 144, 190)}, button={'game': (128, 384, 248, 432)}, file={'game': './assets/game/mian_window/HOME_4TEM_FOLLOW_CANCEL.png'})
HOME_5TEM_FOLLOW = Button(area={'game': (0, 440, 120, 496)},text={'game': '召唤跟随'}, color={'game': (99, 132, 174)}, button={'game': (0, 440, 120, 496)}, file={'game': './assets/game/mian_window/HOME_5TEM_FOLLOW.png'})
HOME_5TEM_FOLLOW_CANCEL = Button(area={'game': (128, 440, 248, 488)},text={'game': '取消跟随'}, color={'game': (101, 137, 183)}, button={'game': (128, 440, 248, 488)}, file={'game': './assets/game/mian_window/HOME_5TEM_FOLLOW_CANCEL.png'})
HOME_ACTIVE = Button(area={'game': (984, 48, 1032, 72)},text={'game': '活云'}, color={'game': (128, 84, 51)}, button={'game': (984, 24, 1040, 64)}, file={'game': './assets/game/mian_window/HOME_ACTIVE.png'})
HOME_DRUG_QUICK = Button(area={'game': (904, 648, 952, 688)},text={'game': ''}, color={'game': (78, 75, 80)}, button={'game': (904, 648, 952, 688)}, file={'game': './assets/game/mian_window/HOME_DRUG_QUICK.png'})
HOME_GUA_JI_HAVE = Button(area={'game': (1168, 296, 1280, 392)},text={'game': '挂机中'}, color={'game': (86, 98, 63)}, button={'game': (1208, 320, 1264, 360)}, file={'game': './assets/game/mian_window/HOME_GUA_JI_HAVE.png'})
HOME_GUA_JI_NOT = Button(area={'game': (1200, 304, 1264, 392)},text={'game': '挂机'}, color={'game': (103, 91, 70)}, button={'game': (1208, 320, 1264, 360)}, file={'game': './assets/game/mian_window/HOME_GUA_JI_NOT.png'})
HOME_MAP_LINE = Button(area={'game': (1128, 24, 1280, 56)},text={'game': '137，78分线1'}, color={'game': (69, 83, 85)}, button={'game': (1128, 24, 1280, 56)}, file={'game': './assets/game/mian_window/HOME_MAP_LINE.png'})
HOME_MAP_TITLE = Button(area={'game': (1120, 0, 1280, 32)},text={'game': '蒲家村'}, color={'game': (40, 69, 96)}, button={'game': (1120, 0, 1280, 32)}, file={'game': './assets/game/mian_window/HOME_MAP_TITLE.png'})
HOME_SELECT_TASK = Button(area={'game': (0, 136, 120, 192)},text={'game': '任务'}, color={'game': (135, 168, 196)}, button={'game': (0, 136, 120, 192)}, file={'game': './assets/game/mian_window/HOME_SELECT_TASK.png'})
HOME_SELECT_TEAM = Button(area={'game': (128, 136, 192, 192)},text={'game': '队伍'}, color={'game': (121, 152, 177)}, button={'game': (128, 136, 192, 192)}, file={'game': './assets/game/mian_window/HOME_SELECT_TEAM.png'})
HOME_SKILL_BUTTON1 = Button(area={'game': (1000, 632, 1056, 688)},text={'game': ''}, color={'game': (52, 86, 84)}, button={'game': (1000, 632, 1056, 688)}, file={'game': './assets/game/mian_window/HOME_SKILL_BUTTON1.png'})
HOME_SKILL_BUTTON2 = Button(area={'game': (1000, 520, 1064, 568)},text={'game': ''}, color={'game': (136, 104, 68)}, button={'game': (1000, 520, 1064, 568)}, file={'game': './assets/game/mian_window/HOME_SKILL_BUTTON2.png'})
HOME_SKILL_BUTTON3 = Button(area={'game': (1088, 448, 1152, 496)},text={'game': ''}, color={'game': (137, 90, 20)}, button={'game': (1088, 448, 1152, 496)}, file={'game': './assets/game/mian_window/HOME_SKILL_BUTTON3.png'})
HOME_SKILL_BUTTON4 = Button(area={'game': (1200, 440, 1264, 488)},text={'game': ''}, color={'game': (120, 49, 28)}, button={'game': (1200, 440, 1264, 488)}, file={'game': './assets/game/mian_window/HOME_SKILL_BUTTON4.png'})
HOME_SKILL_BUTTON5 = Button(area={'game': (1120, 560, 1184, 608)},text={'game': ''}, color={'game': (141, 115, 53)}, button={'game': (1120, 560, 1184, 608)}, file={'game': './assets/game/mian_window/HOME_SKILL_BUTTON5.png'})
HOME_TASK_FIRST_COMM = Button(area={'game': (8, 200, 240, 264)},text={'game': '宝图任务（11/20)在老板娘处探得的消'}, color={'game': (54, 57, 44)}, button={'game': (8, 200, 240, 264)}, file={'game': './assets/game/mian_window/HOME_TASK_FIRST_COMM.png'})
HOME_TASK_FIRST_IS_YAO = Button(area={'game': (0, 192, 200, 240)},text={'game': '1妖兽入侵！'}, color={'game': (68, 39, 66)}, button={'game': (0, 192, 200, 240)}, file={'game': './assets/game/mian_window/HOME_TASK_FIRST_IS_YAO.png'})
